name: Tests

on:
  push:
    branches: [ main ]

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y -f build-essential g++ cmake dos2unix
      - name: Configure GoogleTest
        run: |
          git clone https://github.com/google/googletest /usr/src/googletest
          mkdir /usr/src/googletest/build
          cd /usr/src/googletest/build && cmake .. -DBUILD_GMOCK=OFF
          make
          cd /usr/src
  build:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Configure files to unix line feed
        run: dos2unix test_runner.sh --safe --quiet
      - name: Build project
        run: |
          make clean
          make
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Test runner
        run: ./tappityTest
      - name: Coverage analysis
        run: gcov -b tappity.cpp
